# -*- coding: utf-8 -*-
"""Fund Comparator Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cgDbohqEpOMob_JOhOiPCPUdjlYHzQD
"""

# Google Colab – Informe estilo Morningstar

# 1) Instalación de dependencias e imports
!pip install pandas numpy matplotlib seaborn pandas_datareader adjustText requests beautifulsoup4

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates
from matplotlib.dates import DateFormatter
import matplotlib.ticker as mtick
import matplotlib.colors as mcolors
import pandas_datareader.data as web
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.gridspec import GridSpec
from google.colab import files
from adjustText import adjust_text
import requests
from bs4 import BeautifulSoup
import time
import re

# 2) Configuración de estilo

# Paleta pastel suave para formato condicional y estilos
palette = ["#C0F0D8", "#06C264", "#C0CDCC", "#406666","darkred", "#003334", "darkorange", "darkmagenta" , "mediumturquoise" , "red" , "royalblue" , "greenyellow"]
header_bg = palette[1]
header_txt = "#F1F1F1"

# Configuración global de estilo
sns.set_style("whitegrid")
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 10,
    "axes.titlesize": 14,
    "axes.labelsize": 11,
    "legend.fontsize": 9,
    "figure.titlesize": 16,
    "axes.linewidth": 1.2,
    "grid.alpha": 0.3,
    "axes.edgecolor": "#333333",
    "axes.axisbelow": True
})

# 3) Carga de Excel y metadatos
print("👉 Sube el Excel (hoja 1: NAV series; hoja 2: metadata de fondos):")
uploaded = files.upload()
fname = next(iter(uploaded))

df = pd.read_excel(fname, sheet_name=0)
meta = pd.read_excel(fname, sheet_name=1)

# 4) Preparación de datos
df.iloc[:,0] = pd.to_datetime(df.iloc[:,0])
df.set_index(df.columns[0], inplace=True)
df.sort_index(inplace=True)
df.fillna(method="ffill", inplace=True)

# 5) Funciones optimizadas para Financial Times
def get_gbp_usd_rate():
    """Obtiene el tipo de cambio GBP/USD desde múltiples fuentes"""
    try:
        end_date = pd.Timestamp.now()
        start_date = end_date - pd.DateOffset(days=30)

        # Intentar múltiples fuentes
        sources = [
            ('DEXUSUK', 'fred', 'DEXUSUK'),
            ('GBPUSD=X', 'yahoo', 'Close')
        ]

        for symbol, source, col in sources:
            try:
                data = web.DataReader(symbol, source, start_date, end_date)
                if not data.empty:
                    return data[col].dropna().iloc[-1]
            except:
                continue

        return 1.28  # Backup
    except:
        return 1.28

def parse_fund_size(fund_size_text):
    """Parsea el texto del fund size y convierte a USD"""
    patterns = [
        r'([\d,\.]+)\s*(bn|billion|m|million|k|thousand)\s*(GBP|gbp)',
        r'([\d,\.]+)\s*(GBP|gbp)\s*(bn|billion|m|million|k|thousand)',
        r'([\d,\.]+)(bn|m|k)\s*<[^>]*>GBP',
        r'([\d,\.]+)\s*(bn|m|k)'
    ]

    for pattern in patterns:
        match = re.search(pattern, fund_size_text, re.IGNORECASE)
        if match:
            try:
                value = float(match.group(1).replace(',', ''))
                multiplier = match.group(2).lower() if len(match.groups()) >= 2 else 'm'

                multipliers = {'bn': 1000, 'billion': 1000, 'm': 1, 'million': 1, 'k': 0.001, 'thousand': 0.001}
                value_gbp_millions = value * multipliers.get(multiplier, 1)

                return value_gbp_millions * get_gbp_usd_rate()
            except ValueError:
                continue
    return None

def get_ft_data(isin):
    """Extrae ratings, fund size y launch date de Financial Times"""
    try:
        # Ratings desde página de ratings
        ratings_url = f"https://markets.ft.com/data/funds/tearsheet/ratings?s={isin}:USD"
        resp = requests.get(ratings_url, timeout=10)
        soup = BeautifulSoup(resp.text, "html.parser")

        # Morningstar Stars & Category
        ms_stars = category = None
        ms_app = soup.find("div", {"data-module-name": "MorningstarRatingApp"})
        if ms_app:
            highlighted = ms_app.select_one("span[data-mod-stars-highlighted]")
            ms_stars = len(highlighted.find_all("i", class_="mod-icon--star--filled")) if highlighted else None

            cat_div = ms_app.find("div", class_="mod-morningstar-rating-app__category")
            if cat_div:
                spans = cat_div.find_all("span")
                category = spans[1].get_text(strip=True) if len(spans) > 1 else None

        # Lipper Rating
        lr_rating = None
        lr_app = soup.find("div", {"data-module-name": "LipperRatingApp"})
        if lr_app:
            table = lr_app.find("table", class_="mod-ui-table")
            if table and table.thead and table.tbody:
                headers = [th.get_text(strip=True) for th in table.thead.find_all("th")]
                if "Total return" in headers:
                    col_idx = headers.index("Total return")
                    for row in table.tbody.find_all("tr"):
                        label_cell = row.find("td", class_="mod-ui-table__cell--text")
                        if label_cell and label_cell.get_text(strip=True) == "Overall rating":
                            cells = row.find_all("td")
                            if len(cells) > col_idx:
                                cell = cells[col_idx]
                                icon = cell.find("i")
                                if icon and icon.get("class"):
                                    for c in icon["class"]:
                                        if c.startswith("mod-sprite-lipper-") and c.split("-")[-1].isdigit():
                                            lr_rating = int(c.split("-")[-1])
                                            break
                            break

        # Fund Size y Launch Date desde summary
        summary_url = f"https://markets.ft.com/data/funds/tearsheet/summary?s={isin}:USD"
        resp_summary = requests.get(summary_url, timeout=10)
        soup_summary = BeautifulSoup(resp_summary.text, "html.parser")

        fund_size_usd = launch_date = None
        for table in soup_summary.find_all("table", class_="mod-ui-table--two-column"):
            for row in table.find_all("tr"):
                th = row.find("th")
                if th:
                    header_text = th.get_text(strip=True).lower()
                    td = row.find("td")
                    if td:
                        cell_content = td.get_text(strip=True)

                        if "fund size" in header_text:
                            fund_size_usd = parse_fund_size(cell_content)
                        elif header_text == "launch date":
                            launch_date = cell_content
                            break

        return ms_stars, category, lr_rating, fund_size_usd, launch_date

    except Exception as e:
        print(f"Error procesando ISIN {isin}: {e}")
        return None, None, None, None, None

# 6) Preparación de datos de fondos
fund_codes = df.columns.tolist()
name_map = dict(zip(meta['Codigo'].str[:7], meta['Nombre']))

# Mapear ISINs
isin_map = {}
if 'ISIN' in meta.columns:
    for _, row in meta.iterrows():
        code_key = str(row['Codigo'])[:7]
        isin_map[code_key] = row['ISIN']

display_names = [fund_codes[0]] + [name_map.get(code[:7], code) for code in fund_codes[1:]]
bm_col = fund_codes[0]
funds = fund_codes[1:]
fund_names = display_names[1:]

# 7) Obtener datos de Financial Times
print("🔍 Obteniendo datos de Financial Times...")
ratings_data = []

for fund_code in funds:
    code_key = fund_code[:7]
    fund_name = name_map.get(code_key, fund_code)
    isin = isin_map.get(code_key)

    if isin:
        print(f"Procesando {fund_name} (ISIN: {isin})...")
        ms_stars, category, lr_rating, fund_size_usd, launch_date = get_ft_data(isin)
        time.sleep(1)
    else:
        print(f"ISIN no encontrado para {fund_name}")
        ms_stars, category, lr_rating, fund_size_usd, launch_date = None, None, None, None, None

    ratings_data.append({
        "Fondo": fund_name,
        "ISIN": isin,
        "MS Stars": ms_stars,
        "Categoría": category,
        "Lipper Rating": lr_rating,
        "Fund Size": fund_size_usd,
        "Share Class Inception": launch_date
    })

ratings_df = pd.DataFrame(ratings_data)
print("\n📊 Tabla de datos obtenida:")
print(ratings_df)

# 8) Cálculos de series básicas
fecha_fin = df.index[-1]
start_3y = fecha_fin - pd.DateOffset(years=3)
start_5y = fecha_fin - pd.DateOffset(years=5)

growth = df.divide(df.iloc[0]).multiply(100)
growth_ret = growth - 100
daily = df.pct_change().dropna()
annual_rets = df.resample("Y").last().pct_change().dropna()
annual_rets.index = annual_rets.index.year
drawdown = (df - df.cummax()) / df.cummax()

# 9) Función de métricas
def compute_stats(s, start, end):
    sub = s[start:end]
    total = sub.iloc[-1]/sub.iloc[0] - 1
    years = (sub.index[-1] - sub.index[0]).days / 365.25
    ann = (1+total)**(1/years) - 1
    dr = sub.pct_change().dropna()
    vol = dr.std() * np.sqrt(252)
    neg = dr[dr<0]
    dd = neg.std() * np.sqrt(252)
    sharpe = ann/vol if vol else np.nan
    sortino = ann/dd if dd else np.nan
    return ann, vol, sharpe, sortino

# 10) Función para aplicar estilos consistentes
def apply_chart_style(ax, title):
    ax.set_title(title, weight="bold", fontsize=14, pad=20, color="#2C3E50")
    for spine in ax.spines.values():
        spine.set_linewidth(1.2)
        spine.set_color("#555555")
    ax.grid(True, alpha=0.3, linewidth=0.8)
    ax.set_axisbelow(True)
    ax.tick_params(labelsize=9, colors="#333333")


# 11) Función para generar Página 4 con Opción 5 (Híbrida)
def generate_page_4_option5(pdf, page, df, drawdown, fund_codes, name_map,
                            header_bg, header_txt, footer_func):
    """
    Genera las Páginas 4A y 4B con días de recuperación y detalles completos
    """

    # Identificar benchmark y fondos
    bm_col = fund_codes[0]
    funds = fund_codes[1:]

    # Años disponibles
    years = sorted(df.index.year.unique())

    # =================================================================
    # CALCULAR DATOS DE RECUPERACIÓN
    # =================================================================

    all_results = []
    recovery_matrix = {fund: {} for fund in funds}

    for fund in funds:
        fund_data = df[fund].dropna()
        if len(fund_data) == 0:
            continue

        running_max = fund_data.cummax()
        drawdown_series = (fund_data - running_max) / running_max

        for year in years:
            year_mask = fund_data.index.year == year
            year_data = fund_data[year_mask]

            if len(year_data) == 0:
                continue

            year_dd = drawdown_series[year_mask]
            mdd_value = year_dd.min()

            if pd.isna(mdd_value) or abs(mdd_value) < 0.001:
                # No hubo drawdown significativo en este año → 0 días
                recovery_matrix[fund][year] = 0
                continue

            mdd_date = year_dd.idxmin()
            nav_at_mdd = fund_data.loc[mdd_date]
            peak_value = running_max.loc[mdd_date]

            # Encontrar fecha del peak
            peak_dates = fund_data[fund_data.index <= mdd_date][fund_data >= peak_value * 0.9999]
            if len(peak_dates) > 0:
                peak_date = peak_dates.index[-1]
            else:
                peak_date = fund_data[fund_data.index <= mdd_date].idxmax()
                peak_value = fund_data.loc[peak_date]

            # Buscar recuperación
            post_mdd = fund_data[fund_data.index > mdd_date]
            recovery_mask = post_mdd >= peak_value

            if recovery_mask.any():
                recovery_date = post_mdd[recovery_mask].index[0]
                recovery_days = (recovery_date - mdd_date).days
                nav_at_recovery = fund_data.loc[recovery_date]
            else:
                recovery_date = None
                recovery_days = None
                nav_at_recovery = None

            recovery_matrix[fund][year] = recovery_days

            all_results.append({
                'Fondo_Code': fund,
                'Fondo': name_map.get(fund[:7], fund),
                'Año': year,
                'Peak_Date': peak_date,
                'Peak_NAV': peak_value,
                'MDD_Date': mdd_date,
                'MDD_NAV': nav_at_mdd,
                'DD_Pct': mdd_value * 100,
                'Recovery_Date': recovery_date,
                'Recovery_NAV': nav_at_recovery,
                'Recovery_Days': recovery_days,
            })

    results_df = pd.DataFrame(all_results)

    # Crear matriz de días de recuperación
    recovery_df_temp = pd.DataFrame(recovery_matrix).T
    recovery_df_temp.index = [name_map.get(f[:7], f) for f in recovery_df_temp.index]
    recovery_df = recovery_df_temp.copy()

    # Calcular mediana: incluir 0s (sin DD), pero tratar None como valor muy alto para fondos sin recuperación
    recovery_df['Mediana'] = recovery_df.apply(
        lambda row: row.replace({None: 9999}).median(),  # None → 9999 para penalizar fondos sin recuperación
        axis=1
    )

    # Identificar referencias (peaks comunes)
    peak_groups = {}
    ref_counter = 1

    for idx, row in results_df.iterrows():
        peak_key = f"{row['Peak_Date'].strftime('%Y-%m')}"
        if peak_key not in peak_groups:
            peak_groups[peak_key] = {
                'ref': ref_counter,
                'peak_date': row['Peak_Date'],
                'description': f"Peak {row['Peak_Date'].strftime('%b-%Y')}"
            }
            ref_counter += 1

    # Crear mapeo de referencias
    ref_map = {}
    for idx, row in results_df.iterrows():
        peak_key = f"{row['Peak_Date'].strftime('%Y-%m')}"
        ref_num = peak_groups[peak_key]['ref']
        fund_name = row['Fondo']
        if fund_name not in ref_map:
            ref_map[fund_name] = {}
        ref_map[fund_name][row['Año']] = ref_num

    # =================================================================
    # PÁGINA 4A: TABLA RESUMEN CON REFERENCIAS
    # =================================================================

    num_funds = len(funds)
    fig_height = min(12, max(8, num_funds * 0.8 + 4))

    fig = plt.figure(figsize=(14, fig_height))
    gs = GridSpec(3, 1, figure=fig, height_ratios=[0.6, 0.3, 0.1], hspace=0.15)

    # --- TABLA PRINCIPAL ---
    ax1 = fig.add_subplot(gs[0])
    ax1.axis('off')

    # Preparar datos
    table_data = []
    display_fund_names = [name_map.get(f[:7], f) for f in funds]

    for fund_name in display_fund_names:
        # Fila con días
        row_days = [fund_name]
        for year in years:
            days = recovery_df.loc[fund_name, year] if year in recovery_df.columns else None
            if pd.notna(days):
                row_days.append(f"{int(days)}")
            else:
                row_days.append("-")

        mediana = recovery_df.loc[fund_name, 'Mediana']
        row_days.append(f"{int(mediana)}" if pd.notna(mediana) else "-")

        # Fila con referencias
        row_refs = [""]
        for year in years:
            ref_num = ref_map.get(fund_name, {}).get(year, '')
            row_refs.append(f"[{ref_num}]" if ref_num else "")
        row_refs.append("")

        table_data.append(row_days)
        table_data.append(row_refs)

    col_headers = ['Fondo'] + [str(y) for y in years] + ['Mediana']

    # Crear tabla
    table = ax1.table(cellText=table_data, colLabels=col_headers,
                     cellLoc='center', loc='center',
                     colColours=[header_bg]*len(col_headers),
                     bbox=[0.02, 0.1, 0.96, 0.85])

    table.auto_set_font_size(False)
    base_font = max(6, 10 - num_funds // 3)
    table.set_fontsize(base_font)
    table.scale(1, 1.8)

    # Calcular anchos de columna
    num_year_cols = len(years)
    year_col_width = 0.45 / num_year_cols
    col_widths = [0.35] + [year_col_width] * num_year_cols + [0.12]

    # Aplicar estilos
    for (i, j), cell in table.get_celld().items():
        cell.set_width(col_widths[j])

        if i == 0:  # Header
            cell.set_facecolor(header_bg)
            cell.get_text().set_color(header_txt)
            cell.get_text().set_weight('bold')
            cell.get_text().set_fontsize(base_font + 1)
            cell.set_height(0.08)
        else:
            fund_idx = (i - 1) // 2
            bg_color = '#FFFFFF' if fund_idx % 2 == 0 else '#F8F9FA'
            cell.set_facecolor(bg_color)
            cell.set_height(0.045 if i % 2 == 1 else 0.03)

            # Filas con números
            if i % 2 == 1:
                cell.get_text().set_fontsize(base_font)
                cell.get_text().set_weight('bold')

                # Colormap
                if j > 0 and j < len(col_headers) - 1:
                    try:
                        val = int(table_data[i-1][j]) if table_data[i-1][j] != '-' else None
                        if val is not None:
                            if val <= 100:
                                color = '#D4EDDA'
                            elif val <= 500:
                                color = '#FFF3CD'
                            else:
                                color = '#F8D7DA'
                            cell.set_facecolor(color)
                    except:
                        pass

                if j == len(col_headers) - 1:
                    cell.set_facecolor('#E8F4FD')

            # Filas con referencias
            else:
                cell.get_text().set_fontsize(base_font - 1)
                cell.get_text().set_color('#666666')
                cell.get_text().set_style('italic')

            if j == 0:
                cell.get_text().set_ha('left')
                name_length = len(str(table_data[i-1][j] if i > 0 else ""))
                if name_length > 30:
                    cell.get_text().set_fontsize(max(6, base_font - 2))
                    cell.get_text().set_wrap(True)
            else:
                cell.get_text().set_ha('center')

            cell.set_edgecolor('#E0E0E0')
            cell.set_linewidth(0.5)

        cell.get_text().set_va('center')

    # Título
    fig.text(0.5, 0.96, "RESILIENCIA: Días para Recuperar Peak Histórico tras MDD del Año",
             ha='center', va='center', fontsize=14, fontweight='bold', color="#2C3E50")

    # --- PANEL DE REFERENCIAS ---
    ax2 = fig.add_subplot(gs[1])
    ax2.axis('off')

    ref_text = "REFERENCIAS - PEAKS HISTÓRICOS\n" + "─"*80 + "\n\n"

    sorted_peaks = sorted(peak_groups.items(), key=lambda x: x[1]['ref'])

    for peak_key, peak_info in sorted_peaks:
        ref_num = peak_info['ref']
        desc = peak_info['description']
        ref_text += f"[{ref_num}] {desc}    "
        if ref_num % 4 == 0:
            ref_text += "\n"

    ax2.text(0.05, 0.95, ref_text, transform=ax2.transAxes,
             ha='left', va='top', fontsize=9,
             family='monospace',
             bbox=dict(boxstyle="round,pad=0.5", facecolor="white",
                      edgecolor='#06C264', linewidth=1.5, alpha=0.95))

    # --- NOTA INTERPRETACIÓN ---
    ax3 = fig.add_subplot(gs[2])
    ax3.axis('off')

    note = "Verde = recuperación rápida (<100d) | Amarillo = moderada (100-500d) | Rojo = lenta (>500d) | Ver siguiente página para detalles"
    ax3.text(0.5, 0.5, note, transform=ax3.transAxes,
             ha='center', va='center', fontsize=9,
             style='italic', color='#555555')

    fig.text(0.5, 0.02, f"Página {page}A - Vista Resumen", ha="center",
             fontsize=9, color="#666666", style='italic')
    fig.text(0.1, 0.05, "─" * 80, ha="left", fontsize=8, color="#CCCCCC")

    pdf.savefig(fig, bbox_inches="tight", facecolor='white', dpi=300)
    plt.close(fig)

    # =================================================================
    # PÁGINA 4B: TABLA DE DETALLES COMPLETOS
    # =================================================================

    num_rows = len(results_df)
    fig_height = min(20, max(11, num_rows * 0.35 + 2))

    fig = plt.figure(figsize=(16, fig_height))
    ax = fig.add_subplot(111)
    ax.axis('off')

    # Preparar datos detallados
    detail_data = []
    current_fund = None

    for idx, row in results_df.iterrows():
        if row['Fondo'] != current_fund:
            detail_data.append([row['Fondo'], '', '', '', '', '', '', ''])
            current_fund = row['Fondo']

        detail_row = [
            f"  {row['Año']}",
            f"{row['DD_Pct']:.2f}%",
            row['Peak_Date'].strftime('%d-%b-%y'),
            f"{row['Peak_NAV']:.2f}",
            row['MDD_Date'].strftime('%d-%b-%y'),
            f"{row['MDD_NAV']:.2f}",
            row['Recovery_Date'].strftime('%d-%b-%y') if pd.notna(row['Recovery_Date']) else 'No recup.',
            f"{int(row['Recovery_Days'])}" if pd.notna(row['Recovery_Days']) else '-'
        ]
        detail_data.append(detail_row)

    col_headers = ['Fondo/Año', 'DD %', 'Peak Hist.\nFecha', 'Peak\nNAV',
                   'MDD\nFecha', 'MDD\nNAV', 'Recovery\nFecha', 'Días\nRecup']

    detail_table = ax.table(cellText=detail_data, colLabels=col_headers,
                           cellLoc='center', loc='center',
                           colColours=[header_bg]*len(col_headers),
                           bbox=[0.02, 0.05, 0.96, 0.92])

    detail_table.auto_set_font_size(False)
    detail_table.set_fontsize(7)

    total_rows = len(detail_data) + 1
    base_height = 0.87 / total_rows
    detail_table.scale(1, base_height * 12)

    col_widths_detail = [0.28, 0.08, 0.10, 0.10, 0.10, 0.10, 0.12, 0.08]

    for (i, j), cell in detail_table.get_celld().items():
        cell.set_width(col_widths_detail[j])

        if i == 0:
            cell.set_facecolor(header_bg)
            cell.get_text().set_color(header_txt)
            cell.get_text().set_weight('bold')
            cell.get_text().set_fontsize(7)
        else:
            is_fund_header = detail_data[i-1][1] == ''

            if is_fund_header:
                cell.set_facecolor('#E8F4FD')
                cell.get_text().set_weight('bold')
                cell.get_text().set_fontsize(7)
                if j == 0:
                    name_length = len(str(detail_data[i-1][j]))
                    if name_length > 30:
                        cell.get_text().set_fontsize(6)
                        cell.get_text().set_wrap(True)
            else:
                cell.set_facecolor('#FFFFFF' if i % 2 == 0 else '#F8F9FA')
                cell.get_text().set_fontsize(7)

                if j == 1:
                    try:
                        dd_val = float(detail_data[i-1][j].replace('%', ''))
                        if dd_val <= -40:
                            cell.set_facecolor('#F8D7DA')
                        elif dd_val <= -25:
                            cell.set_facecolor('#FFF3CD')
                        else:
                            cell.set_facecolor('#D4EDDA')
                    except:
                        pass

            cell.get_text().set_ha('left' if j == 0 else 'center')
            cell.set_edgecolor('#E0E0E0')
            cell.set_linewidth(0.5)

        cell.get_text().set_va('center')

    fig.text(0.5, 0.97, "Detalles Completos: Drawdown Y Recuperación",
             ha='center', va='center', fontsize=14, fontweight='bold', color="#2C3E50")

    fig.text(0.5, 0.02, f"Página {page}B - Vista Detallada", ha="center",
             fontsize=9, color="#666666", style='italic')

    fig.text(0.1, 0.05, "─" * 80, ha="left", fontsize=8, color="#CCCCCC")

    pdf.savefig(fig, bbox_inches="tight", facecolor='white', dpi=300)
    plt.close(fig)

    return page + 1  # Incrementar página


# 12) Preparación de datos para PDF
daily_bm = daily[bm_col]
cap_data = {"Up Capture": [], "Down Capture": []}
for code in funds:
    r = daily[code]
    cap_data["Up Capture"].append(r[daily_bm>0].mean() / daily_bm[daily_bm>0].mean())
    cap_data["Down Capture"].append(r[daily_bm<0].mean() / daily_bm[daily_bm<0].mean())
cap_df = pd.DataFrame(cap_data, index=fund_names).round(4)

# Risk-Reward calculations
rr3, rr5 = [], []
for code, name in zip(fund_codes, display_names):
    a3, v3, _, _ = compute_stats(df[code], start_3y, fecha_fin)
    a5, v5, _, _ = compute_stats(df[code], start_5y, fecha_fin)
    rr3.append((v3, a3))
    rr5.append((v5, a5))

rr3_df = pd.DataFrame(rr3, index=display_names, columns=["Volatilidad","Retorno"])
rr5_df = pd.DataFrame(rr5, index=display_names, columns=["Volatilidad","Retorno"])

# Correlación
corr_m = daily.corr().round(4)

# Métricas extendidas
dgs5 = web.DataReader('DGS5','fred', df.index[0], df.index[-1]).dropna()
rf_daily = dgs5['DGS5'].div(100).div(252)
ann_bm = rr5_df.loc[display_names[0], "Retorno"]

metrics_ext = {}
for code, name in zip(fund_codes, display_names):
    r = daily[code]
    ann = rr5_df.loc[name, "Retorno"]
    rf_ann = rf_daily.mean() * 252
    vol = r.std() * np.sqrt(252)
    neg = r[r<0]
    dd = neg.std() * np.sqrt(252)
    sharpe = (ann - rf_ann)/vol if vol else np.nan
    active = ann - ann_bm
    te = (r - daily[bm_col]).std() * np.sqrt(252)
    ir = active/te if te else np.nan
    sortino = (ann - rf_ann)/dd if dd else np.nan

    reg = pd.concat([daily[bm_col]-rf_daily, r-rf_daily], axis=1).dropna()
    if reg.shape[0]>2 and reg.iloc[:,0].nunique()>1:
        slope, intercept = np.polyfit(reg.iloc[:,0], reg.iloc[:,1], 1)
        beta, alpha = slope, intercept * 252
    else:
        beta, alpha = np.nan, np.nan

    metrics_ext[name] = {
        "Retorno Ann": ann, "RF Rate": rf_ann, "Volatilidad Ann": vol, "Downside Dev": dd,
        "Sharpe": sharpe, "Info Ratio": ir, "Sortino": sortino, "Beta": beta, "Alpha": alpha
    }

metrics_ext_df = pd.DataFrame(metrics_ext).T.round(6)

# 13) Funciones auxiliares para formateo
def format_table_data(ratings_table):
    """Formatea los datos de la tabla de ratings"""
    ratings_table = ratings_table.fillna('-')

    # Formatear valores
    for col in ['MS Stars', 'Lipper Rating']:
        ratings_table[col] = ratings_table[col].apply(
            lambda x: f"{int(x)}" if pd.notna(x) and x != '-' else '-'
        )

    # Formatear Fund Size en MILLONES
    def format_fund_size(value):
        if pd.isna(value) or value == '-':
            return '-'
        try:
            # Formatear con separador de miles y 1 decimal
            return f"{value:,.1f}"
        except:
            return '-'

    ratings_table['Fund Size'] = ratings_table['Fund Size'].apply(format_fund_size)

    return ratings_table

def calculate_dynamic_widths(data, headers, num_funds):
    """Calcula anchos dinámicos con tabla expandida"""

    # Calcular longitudes máximas por columna
    max_fund_name_length = 0
    max_category_length = 0

    for row in data:
        if row[0] is not None:  # Fondo
            max_fund_name_length = max(max_fund_name_length, len(str(row[0])))
        if len(row) > 3 and row[3] is not None:  # Categoría
            max_category_length = max(max_category_length, len(str(row[3])))

    # Anchos absolutos basados en contenido real
    if max_fund_name_length <= 25:
        fondo_width = 0.25
    elif max_fund_name_length <= 35:
        fondo_width = 0.30
    else:
        fondo_width = 0.35

    if max_category_length <= 20:
        category_width = 0.18
    else:
        category_width = 0.22

    # Anchos fijos optimizados
    col_widths = [
        fondo_width,    # Fondo - dinámico
        0.14,           # ISIN
        0.08,           # Morningstar Stars
        category_width, # Categoría - dinámico
        0.06,           # Lipper Rating
        0.08,           # Fund Size
        0.11            # Share Class Inception
    ]

    return col_widths



# 14) Generación de PDF
with PdfPages("Morningstar_custom_report.pdf") as pdf:
    page = 1

    def footer(fig):
        fig.text(0.5, 0.02, f"Página {page}", ha="center", fontsize=9, color="#666666", style='italic')
        fig.text(0.1, 0.05, "─" * 80, ha="left", fontsize=8, color="#CCCCCC")

    # PÁGINA 1: Tabla de Ratings
    fig = plt.figure(figsize=(14, 8.27))
    ax = fig.add_subplot(111)
    ax.axis('off')

    # Preparar y formatear datos
    ratings_table = format_table_data(ratings_df.copy())
    table_data = ratings_table.values.tolist()
    col_headers = ratings_table.columns.tolist()
    num_funds = len(ratings_df)
    col_widths = calculate_dynamic_widths(table_data, col_headers, num_funds)

    # Crear tabla con altura dinámica basada en número de fondos
    table_height = min(0.7, 0.15 + (num_funds * 0.08))
    table_y_position = 0.85 - table_height

    table = ax.table(cellText=table_data, colLabels=col_headers, cellLoc='center',
                    loc='center', colColours=[header_bg]*len(col_headers),
                    bbox=[0.01, table_y_position, 0.98, table_height]) # Usar casi todo el ancho

    # Ajustar tamaño de fuente basado en número de fondos
    if num_funds <= 5:
        base_font_size = 9
        header_font_size = 8
    elif num_funds <= 8:
        base_font_size = 8
        header_font_size = 7
    else:
        base_font_size = 7
        header_font_size = 6

    table.auto_set_font_size(False)
    table.set_fontsize(base_font_size)

    # Altura de celda dinámica
    cell_height = max(0.08, 0.6 / (num_funds + 1))
    table.scale(1, cell_height * 25)

    # Aplicar estilos
    header_adjustments = {
        2: "Morningstar\nStars",
        4: "Lipper\nRating",
        5: "Fund Size\n(USD Millones)",
        6: "Share Class\nInception"
    }

    alignment_map = {
        0: ('left', 'semibold'), 1: ('center', 'monospace'), 2: ('center', 'normal'),
        3: ('left', None), 4: ('center', 'normal'), 5: ('right', 'normal'), 6: ('center', 'normal')
    }

    for (i, j), cell in table.get_celld().items():
        cell.set_width(col_widths[j])

        if i == 0:  # Headers
            cell.set_facecolor(header_bg)
            cell.get_text().set_color(header_txt)
            cell.get_text().set_fontsize(header_font_size)
            cell.set_height(cell_height * 1.2)

            if j in header_adjustments:
                cell.get_text().set_text(header_adjustments[j])
                cell.get_text().set_fontsize(header_font_size - 1)

            cell.get_text().set_weight('bold')
            cell.set_edgecolor(header_bg)  # ← AÑADIR ESTA LÍNEA (mismo color que fondo = sin borde visible)
            cell.set_linewidth(0)           # ← AÑADIR ESTA LÍNEA (sin grosor de línea)

        else:  # Data rows
            cell.set_facecolor('#FFFFFF' if i % 2 == 0 else '#F8F9FA')
            cell.get_text().set_fontsize(base_font_size)
            cell.set_height(cell_height)
            cell.set_edgecolor('#E0E0E0')
            cell.set_linewidth(0.5)

        # Alineación por columna
        if j in alignment_map:
            align, weight = alignment_map[j]
            cell.get_text().set_ha(align)
            if i > 0 and weight:  # Solo para datos
                if weight == 'monospace':
                    cell.get_text().set_fontfamily('monospace')
                else:
                    cell.get_text().set_fontweight(weight)

            # Manejo especial para nombres largos de fondos
            if j == 0 and i > 0:  # Columna "Fondo", datos
                fund_name = str(table_data[i-1][j])
                if len(fund_name) > 25:
                    # Reducir fuente para nombres largos
                    cell.get_text().set_fontsize(max(6, base_font_size - 1))
                    cell.get_text().set_wrap(True)
                    # Ajustar altura de celda para nombres muy largos
                    if len(fund_name) > 35:
                        cell.set_height(cell_height * 1.3)

            if j == 3:  # Categoría
                cell.get_text().set_wrap(True)
                if i > 0 and len(str(table_data[i-1][j])) > 30:
                    cell.get_text().set_fontsize(base_font_size - 1)

        cell.get_text().set_va('center')

    # Título y elementos decorativos
    fig.text(0.5, 0.92, "Fondos y Características", ha='center', va='center',
            fontsize=20, fontweight='bold', color="#2C3E50",
            bbox=dict(boxstyle="round,pad=0.5", facecolor='#F8F9FA',
                    edgecolor=header_bg, linewidth=1.5))

    fig.text(0.5, 0.87, "Ratings, Clasificaciones y Características Principales",
            ha='center', va='center', fontsize=12, fontweight='normal',
            color='#555555', style='italic')

    fig.add_artist(plt.Line2D([0.1, 0.9], [0.84, 0.84],  # Línea más ancha
                            color=header_bg, linewidth=2, transform=fig.transFigure))

    note_text = ("Fuente: Financial Times | Morningstar Stars: 1-5 estrellas | "
                "Lipper Rating: 1-5 (5 = mejor desempeño)")
    fig.text(0.5, 0.08, note_text, ha='center', va='center', fontsize=10,
            style='italic', color='#555555',
            bbox=dict(boxstyle="round,pad=0.4", facecolor='#F8F9FA',
                    edgecolor=header_bg, alpha=0.9, linewidth=1))


    footer(fig)
    pdf.savefig(fig, bbox_inches="tight", facecolor='white', dpi=300)
    plt.close(fig)
    page += 1

    # PÁGINA 2: Total Return - ORIENTACIÓN HORIZONTAL
    fig, ax = plt.subplots(figsize=(11.69, 8.27))  # Cambio de orientación
    y_min, y_max = growth_ret.min().min(), growth_ret.max().max()

    for i,(code,name) in enumerate(zip(fund_codes, display_names)):
        ls = ':' if code==bm_col else '-'
        lw = 1.5 if code==bm_col else 1.0
        alpha = 0.9 if code==bm_col else 0.8
        ax.plot(growth_ret.index, growth_ret[code], label=name,
                color=palette[i], linestyle=ls, linewidth=lw, alpha=alpha)

    apply_chart_style(ax, "Total Return")
    ax.set_ylabel("Retorno", fontweight='bold')
    ax.set_ylim(y_min, y_max)
    ax.yaxis.set_major_formatter(mtick.FormatStrFormatter('%.0f%%'))
    ax.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    ax.xaxis.set_major_formatter(DateFormatter('%b-%y'))
    fig.autofmt_xdate(rotation=30, ha='right')

    legend = ax.legend(fontsize=8, frameon=False, fancybox=True, shadow=True,
                      framealpha=0.95, edgecolor='#CCCCCC')

    footer(fig)
    pdf.savefig(fig, bbox_inches="tight", facecolor='white', dpi=300)
    plt.close(fig)
    page += 1

    # PÁGINA 3: Retornos Anuales - LEYENDA CORREGIDA INCLUYENDO BENCHMARK
    fig, ax = plt.subplots(figsize=(11.69,8.27))

    bars = annual_rets.plot.bar(ax=ax,
        color=[palette[i] for i in range(len(annual_rets.columns))],
        width=0.75, alpha=0.85, edgecolor='white', linewidth=1.2)

    apply_chart_style(ax, "Retornos Anuales")
    ax.set_ylabel("Retorno", fontweight='bold')
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0,decimals=1))

    # CORRECCIÓN: Incluir ALL display_names (benchmark + fondos)
    handles, _ = ax.get_legend_handles_labels()
    legend = ax.legend(handles, display_names, fontsize=8, frameon=False,  # Cambio aquí
                      fancybox=True, shadow=True, framealpha=0.95, edgecolor='#CCCCCC')

    # Crear lista de etiquetas con sus posiciones
    label_data = []
    for p in ax.patches:
        h = p.get_height()
        x_pos = p.get_x() + p.get_width()/2
        y_pos = h + 0.005*np.sign(h)
        label_data.append({
            'patch': p,
            'x': x_pos,
            'y_original': y_pos,
            'y_adjusted': y_pos,
            'height': h,
            'text': f"{h*100:.1f}%"
        })

    # Agrupar por año (cada grupo de barras)
    num_funds = len(annual_rets.columns)
    num_years = len(annual_rets.index)

    min_separation = 0.004  # Separación mínima entre etiquetas (en unidades del gráfico)

    for year_idx in range(num_years):
        # Obtener etiquetas de este año
        start_idx = year_idx * num_funds
        end_idx = start_idx + num_funds
        year_labels = label_data[start_idx:end_idx]

        # Ordenar por altura
        year_labels_sorted = sorted(year_labels, key=lambda x: x['height'])

        # Ajustar posiciones si están muy cerca
        for i in range(len(year_labels_sorted) - 1):
            current = year_labels_sorted[i]
            next_label = year_labels_sorted[i + 1]

            diff = abs(next_label['y_adjusted'] - current['y_adjusted'])

            if diff < min_separation:
                # Están muy cerca, separar
                if current['height'] >= 0 and next_label['height'] >= 0:
                    # Ambos positivos, mover el más alto hacia arriba
                    next_label['y_adjusted'] = current['y_adjusted'] + min_separation
                elif current['height'] < 0 and next_label['height'] < 0:
                    # Ambos negativos, mover el más bajo hacia abajo
                    current['y_adjusted'] = next_label['y_adjusted'] - min_separation

    # Dibujar las etiquetas con las posiciones ajustadas
    for label in label_data:
        text = ax.text(label['x'], label['y_adjusted'], label['text'],
                      ha='center', va='bottom' if label['height'] >= 0 else 'top',
                      fontsize=7, fontweight='bold', color='#333333')

        # Si se movió mucho, añadir línea conectora sutil
        if abs(label['y_adjusted'] - label['y_original']) > min_separation * 0.5:
            ax.plot([label['x'], label['x']],
                   [label['y_original'], label['y_adjusted']],
                   color='grey', linewidth=0.5, alpha=0.3, linestyle='-')

    footer(fig)
    pdf.savefig(fig, bbox_inches="tight", facecolor='white', dpi=300)
    plt.close(fig)
    page += 1

    # PÁGINA 4: Tabla de Retornos Comparativos (MTD, QTD, YTD, 1Y, 3Y, 5Y)

    # Calcular fechas para los períodos
    fecha_fin_tabla = df.index[-1]
    end_prev_month = pd.Timestamp(fecha_fin_tabla.year, fecha_fin_tabla.month, 1) - pd.DateOffset(days=1)
    end_prev_quarter = pd.Timestamp(fecha_fin_tabla.year, ((fecha_fin_tabla.month - 1) // 3) * 3 + 1, 1) - pd.DateOffset(days=1)
    end_prev_year = pd.Timestamp(fecha_fin_tabla.year, 1, 1) - pd.DateOffset(days=1)
    start_1y_tabla = fecha_fin_tabla - pd.DateOffset(years=1)
    start_3y_tabla = fecha_fin_tabla - pd.DateOffset(years=3)
    start_5y_tabla = fecha_fin_tabla - pd.DateOffset(years=5)

    # Función para retorno simple
    def compute_simple_ret(s, start, end):
        sub = s[start:end]
        if len(sub) < 2:
            return 0
        return sub.iloc[-1]/sub.iloc[0] - 1

    # Función para retorno anualizado
    def compute_ann_ret(s, start, end):
        sub = s[start:end]
        if len(sub) < 2:
            return 0
        total = sub.iloc[-1]/sub.iloc[0] - 1
        years = (sub.index[-1] - sub.index[0]).days / 365.25
        return (1+total)**(1/years) - 1 if years > 0 else 0

    # Calcular retornos para todos los fondos
    returns_data_tabla = []
    for code, name in zip(fund_codes, display_names):
        returns_data_tabla.append({
            'Fondo': name,
            'MTD': compute_simple_ret(df[code], end_prev_month, fecha_fin_tabla) * 100,
            'QTD': compute_simple_ret(df[code], end_prev_quarter, fecha_fin_tabla) * 100,
            'YTD': compute_simple_ret(df[code], end_prev_year, fecha_fin_tabla) * 100,
            '1Y': compute_ann_ret(df[code], start_1y_tabla, fecha_fin_tabla) * 100,
            '3Y': compute_ann_ret(df[code], start_3y_tabla, fecha_fin_tabla) * 100,
            '5Y': compute_ann_ret(df[code], start_5y_tabla, fecha_fin_tabla) * 100
        })

    returns_df_tabla = pd.DataFrame(returns_data_tabla)

    # Crear figura
    num_funds_tabla = len(returns_df_tabla)
    fig_height = min(11, max(8, num_funds_tabla * 0.8 + 3))

    fig = plt.figure(figsize=(14, fig_height))
    ax = fig.add_subplot(111)
    ax.axis('off')

    # Preparar datos para tabla
    table_data = []
    for idx, row in returns_df_tabla.iterrows():
        table_row = [
            row['Fondo'],
            f"{row['MTD']:.2f}%",
            f"{row['QTD']:.2f}%",
            f"{row['YTD']:.2f}%",
            f"{row['1Y']:.2f}%",
            f"{row['3Y']:.2f}%",
            f"{row['5Y']:.2f}%"
        ]
        table_data.append(table_row)

    col_headers = ['Fondo', 'MTD', 'QTD', 'YTD', '1 Año', '3 Años', '5 Años']

    # Crear tabla
    table = ax.table(cellText=table_data, colLabels=col_headers,
                    cellLoc='center', loc='center',
                    colColours=[header_bg]*len(col_headers),
                    bbox=[0.02, 0.15, 0.96, 0.75])

    table.auto_set_font_size(False)
    base_font = max(8, 11 - num_funds_tabla // 3)
    table.set_fontsize(base_font)
    table.scale(1, 2.5)

    # Anchos de columna
    col_widths = [0.35, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10]

    # Función de formato condicional (3 colores)
    def get_color_simple(value, col_values):
        if value == max(col_values):
            return '#D4EDDA'  # Verde → Mejor
        elif value == min(col_values):
            return '#F8D7DA'  # Rojo → Peor
        else:
            return '#FFFFFF'  # Blanco → Resto

    # Mapeo de headers a columnas del DataFrame
    header_to_col_tabla = {
        'MTD': 'MTD',
        'QTD': 'QTD',
        'YTD': 'YTD',
        '1 Año': '1Y',
        '3 Años': '3Y',
        '5 Años': '5Y'
    }

    # Aplicar estilos
    for (i, j), cell in table.get_celld().items():
        cell.set_width(col_widths[j])

        if i == 0:  # Headers
            cell.set_facecolor(header_bg)
            cell.get_text().set_color(header_txt)
            cell.get_text().set_weight('bold')
            cell.get_text().set_fontsize(base_font)
            cell.set_height(0.08)
            cell.set_edgecolor(header_bg)
            cell.set_linewidth(0)
        else:  # Data rows
            if j == 0:  # Columna Fondo
                cell.set_facecolor('#FFFFFF' if i % 2 == 0 else '#F8F9FA')
                cell.get_text().set_ha('left')
                cell.get_text().set_weight('semibold')

                # Ajustar fuente para nombres largos
                fund_name = table_data[i-1][j]
                if len(fund_name) > 25:
                    cell.get_text().set_fontsize(max(7, base_font - 1))
                    cell.get_text().set_wrap(True)
            else:  # Columnas de datos con formato condicional
                header_name = col_headers[j]
                df_col_name = header_to_col_tabla[header_name]
                col_values = returns_df_tabla[df_col_name].values
                current_value = returns_df_tabla.iloc[i-1][df_col_name]

                color = get_color_simple(current_value, col_values)
                cell.set_facecolor(color)
                cell.get_text().set_weight('bold')
                cell.get_text().set_fontsize(base_font)

            cell.set_height(0.06)
            cell.set_edgecolor('#E0E0E0')
            cell.set_linewidth(0.5)

        cell.get_text().set_va('center')

    # Título
    fig.text(0.5, 0.94, "Retornos Comparativos por Período",
             ha='center', va='center', fontsize=16, fontweight='bold', color="#2C3E50")

    fig.text(0.5, 0.90, "MTD, QTD, YTD: Retornos totales  |  1Y, 3Y, 5Y: Retornos anualizados",
             ha='center', va='center', fontsize=11, style='italic', color='#555555')

    # Footer
    footer(fig)
    pdf.savefig(fig, bbox_inches="tight", facecolor='white', dpi=300)
    plt.close(fig)
    page += 1


    # PÁGINA 5A y 5B: Drawdown y Recuperación (Opción 5 Híbrida)
    page = generate_page_4_option5(
            pdf=pdf,
            page=page,
            df=df,
            drawdown=drawdown,
            fund_codes=fund_codes,
            name_map=name_map,
            header_bg=header_bg,
            header_txt=header_txt,
            footer_func=footer
        )


    # PÁGINA 6: Drawdown Series
    fig, ax = plt.subplots(figsize=(11.69,8.27))
    for i,(code,name) in enumerate(zip(fund_codes, display_names)):
        ls = ':' if code==bm_col else '-'
        lw = 1.5 if code==bm_col else 1.0
        ax.plot(drawdown.index, drawdown[code], label=name, color=palette[i], linestyle=ls, linewidth=lw)

    apply_chart_style(ax, "Drawdown Series")
    ax.set_ylabel("Drawdown")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0, decimals=1))
    ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
    ax.xaxis.set_major_formatter(DateFormatter('%b-%y'))
    fig.autofmt_xdate(rotation=30, ha='right')
    ax.legend(fontsize=8, frameon=False)

    footer(fig)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)
    page += 1

    # PÁGINA 7: Risk-Reward 3 y 5 Años
    bm_a3, bm_v3, _, _ = compute_stats(df[bm_col], start_3y, fecha_fin)
    bm_a5, bm_v5, _, _ = compute_stats(df[bm_col], start_5y, fecha_fin)

    fig, axs = plt.subplots(ncols=2, figsize=(14,6))
    texts3, texts5 = [], []

    # Gráfico 3 años
    ax = axs[0]
    for i, f in enumerate(display_names):
        x, y = rr3_df.loc[f,['Volatilidad','Retorno']]
        ax.scatter(x, y, color=palette[i], s=80)
        texts3.append(ax.text(x, y, f, fontsize=8))

    ax.axhline(bm_a3, color='grey', linestyle='--')
    ax.axvline(bm_v3, color='grey', linestyle='--')
    ax.set_xlabel('Volatilidad Anualizada 3A')
    ax.set_ylabel('Retorno Anualizado 3A')
    ax.set_title('Risk-Reward 3 Años', weight='bold')
    ax.xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0,decimals=1))
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0,decimals=1))
    adjust_text(texts3, ax=ax, arrowprops=dict(arrowstyle='-',color='grey',lw=0.5))

    # Gráfico 5 años
    ax = axs[1]
    for i, f in enumerate(rr5_df.index):
        x, y = rr5_df.loc[f,['Volatilidad','Retorno']]
        ax.scatter(x, y, color=palette[i], s=80)
        texts5.append(ax.text(x, y, f, fontsize=8))

    ax.axhline(bm_a5, color='grey', linestyle='--')
    ax.axvline(bm_v5, color='grey', linestyle='--')
    ax.set_xlabel('Volatilidad Anualizada 5A')
    ax.set_ylabel('Retorno Anualizado 5A')
    ax.set_title('Risk-Reward 5 Años', weight='bold')
    ax.xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0,decimals=1))
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0,decimals=1))
    adjust_text(texts5, ax=ax, arrowprops=dict(arrowstyle='-',color='grey',lw=0.5))

    plt.tight_layout()
    footer(fig)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)
    page += 1

    # PÁGINA 8: Capture Ratios
    fig = plt.figure(figsize=(11.69,11.69))
    gs = GridSpec(2,1, figure=fig, height_ratios=[1,2], hspace=0.4)

    # Tabla de capture ratios
    ax1 = fig.add_subplot(gs[0])
    ax1.axis('off')

    td = cap_df.reset_index().rename(columns={'index':'Fondos'})
    td_formatted = td.copy()
    for col in ['Up Capture', 'Down Capture']:
        td_formatted[col] = (td_formatted[col]*100).round(1).map(lambda x: f"{x:.1f}%")

    table_data = td_formatted.values.tolist()
    col_headers = td_formatted.columns.tolist()

    p2 = ax1.table(cellText=table_data,
                   colLabels=col_headers,
                   cellLoc='center',
                   loc='center',
                   colColours=[header_bg]*len(col_headers))


    p2.auto_set_font_size(False)
    p2.set_fontsize(8)
    p2.scale(1.2,1)

    w2 = [0.3] + [0.7/(len(col_headers)-1)]*(len(col_headers)-1)

    for (i,j), cell in p2.get_celld().items():
        if i == 0:
            cell.set_facecolor(header_bg)
            cell.get_text().set_color(header_txt)
        if j == 0:
            cell.get_text().set_ha('left')
        cell.set_width(w2[j])

    ax1.set_title("Capture Ratios vs Benchmark", pad=12, weight="bold", loc='center')

    # Gráfico scatter
    ax2 = fig.add_subplot(gs[1])
    texts = []
    for i, name in enumerate(fund_names):
        x, y = cap_df.loc[name, ['Up Capture','Down Capture']]
        ax2.scatter(x, y, color=palette[i], s=80)
        texts.append(ax2.text(x, y, name, fontsize=8))

    ax2.axhline(1.0, color=header_bg, linestyle='--')
    ax2.axvline(1.0, color=header_bg, linestyle='--')
    ax2.set_xlabel("Up-Capture")
    ax2.set_ylabel("Down-Capture")
    adjust_text(texts, ax=ax2)

    footer(fig)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)
    page += 1

    # PÁGINA 9: Matriz de Correlación
    mask = np.triu(np.ones_like(corr_m, dtype=bool))
    fig, ax = plt.subplots(figsize=(8.27,8))

    sns.heatmap(corr_m, mask=mask, annot=True, fmt=".2f",
                cmap="coolwarm", vmin=-1, vmax=1,
                annot_kws={"size":8},
                cbar_kws={"shrink":0.6, "label":"Correlación"},
                linewidths=0.5, linecolor="white", ax=ax)

    ax.set_title("Matriz de Correlación de Retornos Diarios", weight="bold", pad=12)
    ax.set_xticklabels(display_names, rotation=45, ha='right')
    ax.set_yticklabels(display_names, rotation=0)

    for s in ax.spines.values():
        s.set_visible(True)
        s.set_color("#333333")
        s.set_linewidth(1)

    footer(fig)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)
    page += 1

    # PÁGINA 10: Métricas Extendidas - ANCHOS DINÁMICOS + ALTURA UNIFORME DE HEADERS
    tbl8 = metrics_ext_df.copy()

    # Formatear métricas como porcentaje
    for col in ["Retorno Ann","RF Rate","Volatilidad Ann","Downside Dev","Alpha"]:
        tbl8[col] = (tbl8[col]*100).round(2).map(lambda x:f"{x:.2f}%")

    # Formatear ratios
    for col in ["Sharpe","Info Ratio","Sortino","Beta"]:
        tbl8[col] = tbl8[col].round(2).map(lambda x:f"{x:.2f}")

    # TRANSPONER LA TABLA: Cambiar filas por columnas
    tbl8_transposed = tbl8.T  # Transponer

    # Identificar el benchmark (primera columna después de transponer)
    if len(tbl8_transposed.columns) > 0:
        # Renombrar la primera columna para indicar que es benchmark
        first_col = tbl8_transposed.columns[0]
        tbl8_transposed = tbl8_transposed.rename(columns={first_col: f"{first_col}\n(Benchmark)"})

        # Para el benchmark, ciertas métricas no aplican
        tbl8_transposed.loc['Info Ratio', tbl8_transposed.columns[0]] = "-"
        tbl8_transposed.loc['Beta', tbl8_transposed.columns[0]] = "-"
        tbl8_transposed.loc['Alpha', tbl8_transposed.columns[0]] = "-"

    # Resetear índice para crear columna de Métricas
    tbl8_transposed = tbl8_transposed.reset_index().rename(columns={'index':'Métricas'})

    # ========== FUNCIÓN: CÁLCULO DINÁMICO DE ANCHOS POR COLUMNA ==========
    def calculate_dynamic_column_widths(col_headers, num_funds):
        """
        Calcula anchos dinámicos para cada columna de fondo según la longitud del nombre.
        """
        # Ancho fijo para columna "Métricas"
        metrics_width = 0.15

        # Calcular longitud de cada header de fondo
        fund_lengths = {}
        total_length_units = 0

        for j, header in enumerate(col_headers):
            if j == 0:  # Columna "Métricas"
                continue

            # Calcular longitud del header (remover salto de línea si existe)
            header_clean = header.replace('\n', ' ')
            length = len(header_clean)

            # Asignar "unidades de ancho" según longitud
            if length <= 20:
                units = 1.0
            elif length <= 30:
                units = 1.3
            elif length <= 40:
                units = 1.6
            else:
                units = 2.0

            fund_lengths[j] = {'length': length, 'units': units}
            total_length_units += units

        # Distribuir espacio restante según unidades
        remaining_width = 1.0 - metrics_width
        col_widths = [metrics_width]

        for j in range(1, len(col_headers)):
            units = fund_lengths[j]['units']
            width = (units / total_length_units) * remaining_width
            col_widths.append(width)

        return col_widths, fund_lengths

    # ========== CALCULAR ANCHOS DINÁMICOS ==========
    table_data = tbl8_transposed.values.tolist()
    col_headers = tbl8_transposed.columns.tolist()

    col_widths, fund_lengths = calculate_dynamic_column_widths(col_headers, len(tbl8_transposed.columns) - 1)

    # Ajustar tamaño de figura según número de fondos
    num_funds = len(col_headers) - 1
    if num_funds <= 5:
        fig_width = 11.69
        base_font_size = 8
        header_font_size = 7
    elif num_funds <= 8:
        fig_width = 14
        base_font_size = 7
        header_font_size = 6
    else:
        fig_width = 16
        base_font_size = 6
        header_font_size = 5

    # ========== DICCIONARIO PARA HEADERS LARGOS CON SALTOS DE LÍNEA ==========
    header_adjustments = {}
    max_num_lines = 1  # 🔧 CRÍTICO: Rastrear el número máximo de líneas

    for j, header in enumerate(col_headers):
        if j > 0:  # Solo para headers de fondos (no "Métricas")
            header_clean = header.replace('\n', ' ')  # Remover salto si ya existe
            length = len(header_clean)

            if length > 20:  # Necesita salto de línea
                words = header_clean.split()

                if len(words) >= 4:
                    # Dividir en 3 líneas si hay muchas palabras
                    third = len(words) // 3
                    line1 = ' '.join(words[:third])
                    line2 = ' '.join(words[third:third*2])
                    line3 = ' '.join(words[third*2:])
                    header_adjustments[j] = f"{line1}\n{line2}\n{line3}"
                    max_num_lines = max(max_num_lines, 3)

                elif len(words) >= 2:
                    # Dividir en 2 líneas
                    mid_point = len(words) // 2
                    line1 = ' '.join(words[:mid_point])
                    line2 = ' '.join(words[mid_point:])
                    header_adjustments[j] = f"{line1}\n{line2}"
                    max_num_lines = max(max_num_lines, 2)

                else:
                    # Una sola palabra muy larga - cortar por mitad
                    mid = len(header_clean) // 2
                    # Buscar espacio o guión cerca del medio
                    cut_point = mid
                    for i in range(mid-5, min(mid+5, len(header_clean))):
                        if i < len(header_clean) and header_clean[i] in [' ', '-']:
                            cut_point = i
                            break
                    header_adjustments[j] = f"{header_clean[:cut_point]}\n{header_clean[cut_point+1:]}"
                    max_num_lines = max(max_num_lines, 2)
            else:
                # Header corto - no necesita ajuste, pero contar como 1 línea
                max_num_lines = max(max_num_lines, 1)

    # 🔧 CRÍTICO: Calcular altura uniforme para TODOS los headers
    uniform_header_height = 0.08 * max_num_lines

    fig, ax = plt.subplots(figsize=(fig_width, len(tbl8_transposed)*0.35+2))
    ax.axis('off')

    p8 = ax.table(cellText=table_data,
                  colLabels=col_headers,
                  cellLoc='center',
                  loc='center',
                  colColours=[header_bg]*len(col_headers))

    p8.auto_set_font_size(False)
    p8.set_fontsize(base_font_size)
    p8.scale(1, 1.8)

    # ========== APLICAR ESTILOS CON ALTURA UNIFORME ==========
    for (i, j), cell in p8.get_celld().items():
        if j < 0:
            continue

        # Aplicar anchos dinámicos calculados
        cell.set_width(col_widths[j])

        if i == 0:  # Encabezados
            cell.set_facecolor(header_bg)
            cell.get_text().set_color(header_txt)
            cell.get_text().set_weight('bold')

            # 🔧 CRÍTICO: Aplicar la MISMA altura a TODOS los headers
            cell.set_height(uniform_header_height)

            # Aplicar texto ajustado si existe
            if j in header_adjustments:
                cell.get_text().set_text(header_adjustments[j])

                # Ajustar fuente según longitud
                length = fund_lengths.get(j, {}).get('length', 0)
                if length > 40:
                    cell.get_text().set_fontsize(max(5, header_font_size - 1))
                else:
                    cell.get_text().set_fontsize(header_font_size)
            else:
                cell.get_text().set_fontsize(header_font_size)

            # Word wrap activado
            cell.get_text().set_wrap(True)

        elif j == 1:  # Primera columna de datos (Benchmark)
            cell.set_facecolor('#E8F4FD')
            cell.set_height(0.08)
            cell.get_text().set_fontsize(base_font_size)

        else:  # Otras columnas de fondos
            # Alternar colores suaves para las filas
            if i % 2 == 0:
                cell.set_facecolor('#FFFFFF')
            else:
                cell.set_facecolor('#F8F9FA')
            cell.set_height(0.08)
            cell.get_text().set_fontsize(base_font_size)

        if j == 0:  # Primera columna (Métricas)
            cell.get_text().set_ha('left')
            cell.get_text().set_weight('semibold')
        else:  # Columnas de datos
            cell.get_text().set_ha('center')

        # Aplicar bordes sutiles
        cell.set_edgecolor('#E0E0E0')
        cell.set_linewidth(0.5)

        # Alineación vertical centrada
        cell.get_text().set_va('center')

    ax.set_title("Métricas Extendidas (5Y)", pad=20, weight="bold", loc='center')

    footer(fig)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

print('✅ PDF generado: Morningstar_custom_report.pdf')
files.download('Morningstar_custom_report.pdf')